services:
  github-runner:
    image: myoung34/github-runner:latest
    environment:
      - RUNNER_NAME=${RUNNER_NAME}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - REPO_URL=${REPO_URL}
      - RUNNER_WORKDIR=/tmp/github-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
