name: Copy configs to machine

#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

on:
  workflow_dispatch

jobs:
  transfer-file:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          - eval `ssh-agent -s`
          - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          - mkdir -p ~/.ssh
          - chmod 700 ~/.ssh

      - name: Transfer server 3 cfg
        run: |
          scp -o StrictHostKeyChecking=no ./server3_SquadAdminTools.cfg $SSH_USER@$SSH_HOST:/root/git_repo/

      - name: Transfer server 4 cfg
        run: |
          scp -o StrictHostKeyChecking=no ./server4_SquadAdminTools.cfg $SSH_USER@$SSH_HOST:/root/git_repo