name: Copy configs to machine

#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

#          - chmod 700 ~/.ssh
#          - eval $(ssh-agent -s)
#          - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
#          - mkdir -p ~/.ssh
on:
  workflow_dispatch

jobs:
  setup:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host remote-server\n  HostName ${{ secrets.SSH_HOST }}\n  User ${{ secrets.SSH_USER }}\n  IdentityFile ~/.ssh/id_rsa\n  StrictHostKeyChecking no" > ~/.ssh/config

  transfer-3:
    runs-on: self-hosted

    steps:
      - name: Transfer server 3 cfg
        run: |
          echo "Copying config to path: ${{ secrets.CONFIG_PATH_TEST }}"
          scp -o StrictHostKeyChecking=no ./server3_SquadAdminTools.cfg ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.CONFIG_PATH_TEST }}

  transfer-4:
    runs-on: self-hosted

    steps:
      - name: Transfer server 4 cfg
        run: |
          echo "Copying config to path: ${{ secrets.CONFIG_PATH_TEST }}"
          scp -o StrictHostKeyChecking=no ./server4_SquadAdminTools.cfg ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.CONFIG_PATH_TEST }}